<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Soltex.App</RootNamespace>
    <AssemblyName>Soltex</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Soltex.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Soltex.RemoteAssist\Soltex.RemoteAssist.csproj" />
    <ProjectReference Include="..\Soltex.Security\Soltex.Security.csproj" />
    <ProjectReference Include="..\Soltex.Update\Soltex.Update.csproj" />
    <ProjectReference Include="..\Soltex.Monitoring\Soltex.Monitoring.csproj" />
    <ProjectReference Include="..\Soltex.DeviceFabric\Soltex.DeviceFabric.csproj" />
    <ProjectReference Include="..\Soltex.Audio\Soltex.Audio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Soltex.App.Tests" />
  </ItemGroup>
</Project>
