<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RootNamespace>WaveSlate.Update.Tests</RootNamespace>
    <AssemblyName>WaveSlate.Update.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WaveSlate.Security\WaveSlate.Security.csproj" />
    <ProjectReference Include="..\..\src\WaveSlate.Update\WaveSlate.Update.csproj" />
  </ItemGroup>
</Project>
